# When setting up don't forget to create the file ~/.zshrc if it does not already exist and paste the following line into it
# . ~/sites/bin/dotfiles/zshrc
# When setting up don't forget to create the file ~/.zshenv if it does not already exist and paste the following line into it
# . ~/sites/bin/dotfiles/zsh/env

. ~/sites/bin/dotfiles/zsh/config
. ~/sites/bin/dotfiles/zsh/aliases

if [[ -f "$HOME/.amazon_keys" ]]; then
  source "$HOME/.amazon_keys";
fi
if [[ -s /Users/i0n/.rvm/scripts/rvm ]] ; then 
  source /Users/i0n/.rvm/scripts/rvm ; 
fi