#!/usr/bin/env ruby
ROOT_PATH = File.expand_path(File.join(File.dirname(__FILE__)))
require 'fileutils'
require 'yaml'
require "#{ROOT_PATH}/folder/inside/gogo.rb"

module Mega

  class Base
    
    def puts(*args)
      @output.puts(*args)    
    end
    
    def initialize
      @output = $stdout
    end
      
  end
  
  class A
    
  end
  
  class B < A
    
    def write
      @testo = 1
    end
    
    def read
      @testo
    end
    
  end
  
  class C < B
  
  end
  
  class D < C
    
  end
  
end

class Object
  
  def eigenclass
    class << self
      self
    end
  end
  
end


obj = Mega::D.new
obj_class = obj.class
puts "eigenclass: #{obj.eigenclass}"
puts "class:      #{obj.class}"
puts "superclass: #{obj_class.superclass}"
puts
puts

##################################################################################################################################################################

# def capture_stdout(&block)
#   original_stdout = $stdout
#   $stdout = fake = StringIO.new
#   begin
#     yield
#   ensure
#     $stdout = original_stdout
#   end
#  fake.string
# end

