#!/usr/bin/env ruby

# Installs a symlink for mvim to ~/bin/mvim so that it will load Vim if called from the terminal

def link_mvim

  vim = %x{which vim}.chomp
  puts "Linking Vim in: #{vim} to /usr/local/bin/mvim"
  exec "ln -s #{vim} /usr/local/bin/mvim" 

end

link_mvim
