#!/usr/bin/env ruby
require_relative "nginx_auto_config.rb"
if ARGV.count < 3
  puts
  puts "******************************************************************************************************************************************"
  puts
  puts "You need to specify three paramters to use this script:\n\n1: The Source File.\n2: The Target File.\n3: The App Name."
  puts
  puts "e.g. nginx_auto_config /Users/i0n/Sites/bin/templates/rails/config/nginx.local.conf /usr/local/nginx/conf/nginx.conf test_app"
  puts
  puts "******************************************************************************************************************************************"
  puts
  exit
else
  `sudo chmod 777 #{ARGV[1]}`
  puts
  puts "******************************************************************************************************************************************"
  puts
  puts "Setting permissions for: #{ARGV[1]}"
  puts
  nginx_auto_config(ARGV[0], ARGV[1], ARGV[2])
end