#!/usr/bin/env ruby
puts "Nginx is being stopped..."
`sudo nginx -s stop`
sleep 5
puts "Nginx is being started..."
`sudo launchctl load -F  /System/Library/LaunchDaemons/nginx.plist`
puts "SUCCESS! Nginx has been restarted!"