#!/bin/bash

# Removes existing bash zsh ssh and vim dotfiles and sets up links to ~/bin/dotfiles

rm -R -f ~/.bash* ~/.profile ~/.zsh* ~/.ssh/config ~/.vim* && ln -s ~/bin/dotfiles/zsh/zshrc ~/.zshrc && ln -s ~/bin/dotfiles/zsh/env ~/.zshenv && ln -s ~/bin/dotfiles/ssh/config ~/.ssh/config && ln -s ~/bin/dotfiles/vim/vimrc ~/.vimrc && ln -s ~/bin/dotfiles/vim ~/.vim && ln -s ~/bin/dotfiles/bash/bashrc ~/.bashrc && ln -s ~/bin/dotfiles/vim/gvimrc ~/.gvimrc
