#!/usr/bin/env ruby

input_value = ARGV.dup
ARGV.clear
current_path = `pwd`.chomp
user = `echo $USER`.chomp

class App
  
  attr_accessor :name, :domain
  
  def initialize(name, domain)
    @name = name
    @domain = domain
  end
  
  def test_input
    self.instance_variables.each do |variable|
      if self.instance_variable_get(variable) == nil
        puts "You must enter a #{variable.to_s.sub(/@/, '')} for the application. Please enter it now."
        self.instance_variable_set(variable, gets.chomp)
      end  
    end
  end    
  
end

app = App.new(input_value[0], input_value[1])
app.test_input

install_path = "/Users/#{user}/sites"
Dir.chdir install_path
begin
  Dir.mkdir app.name
rescue Errno::EEXIST
  puts "**ERROR!!** The application could not be created because the directory #{install_path}/#{app.name} already exists."
  puts "Would you like to rename your application and try again? yes/no?"
  answer = gets.chomp
  if answer == 'yes' || answer == 'y'
    puts "seems to be working"
  else
    exit
  end
rescue Exception => e
  puts "**ERROR!!** There was a problem creating the folder for #{app.name}\n The following error occurred: #{e}"
end



puts "The app name is set to #{app.name}"
puts "The app domain is set to #{app.domain}"
puts current_path
puts current_path.inspect
puts user.inspect