#!/usr/bin/env ruby

require 'eventmachine'

module PlusFeed
  

  class Echo < EventMachine::Connection
     def initialize(*args)
       super
       self.send_file_data('client.dat')
     end
   
     def receive_data(data)
       p data
     end
   end
 
   EventMachine::run {
     connection = EventMachine::connect '127.0.0.1', 8081, Echo
     # connection = EventMachine::connect '198.190.11.21', 4001, Echo
   }
 
end