#!/usr/bin/env ruby

module Testo

  class Project
  
    def initialize(args)
      @args = args
      @input = STDIN
      @output = STDOUT
    end
  
    def start
      @output.puts @args
    end
    
    def ask
      @ask = @input.gets.chomp
      @output.puts @ask
    end
  
  end
  
end

project = Testo::Project.new(ARGV)
project.start
project.ask