#!/usr/bin/env ruby

require 'socket'

# First server.
# connections = Socket.getaddrinfo('198.190.11.21', 4001)

# Second server.
connections = Socket.getaddrinfo('198.190.11.23', 4001)

count = 0
connections.each do |c|
  count += 1
  puts "Connection number: #{count}"
  puts "Address Family:   #{c[0]}"
  puts "Port Number:      #{c[1]}"
  puts "Host Name:        #{c[2]}"
  puts "Host IP Address:  #{c[3]}"
  puts "Protocol Family:  #{c[4]}"
  puts "Socket Type:      #{c[5]}"
  puts "Protocol:         #{c[6]}"
  puts ""
end

# PROTOCOL 6 is TCP
# PROTOCOL 17 is UDP

socket = TCPSocket.open('198.190.11.23', 4001)
data = {:user => 'testdata1', :password => 'testdata1'}
socket.send(data)
response = socket.gets
socket.close