set nocompatible                  " Must come first because it changes other options.
set shell=/bin/zsh

execute pathogen#infect()

" Remove ALL autocommands for the current group.
:autocmd!	

filetype plugin off               " Turn off configuration loaded from plugins
syntax enable                     " Turn on syntax highlighting.

runtime macros/matchit.vim        " Load the matchit plugin.
set runtimepath^=~/bin/dotfiles/vim/bundle/ctrlp.vim

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

"set ignorecase                    " Case-insensitive searching.
"set smartcase                     " But case-sensitive if expression contains a capital letter.

set cmdheight=2                   " Number of lines used for the command-line
set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vimtmp//,    " Keep swap files in one location

set clipboard=unnamed            " Set up clipboard 
map <F2> ;.w !pbcopy<CR><CR>     " Copies the current line to the clipboard.
map <F3> ;r !pbpaste<CR>         " Pastes the current content from the clipboard.

" Whitespace
set tabstop=2 
set expandtab                   " use spaces, not tabs (optional)
set shiftwidth=2 
set softtabstop=2
set backspace=indent,eol,start  " backspace through everything in insert mode
set smarttab autoindent

" Indentation viewer
let g:indent_guides_enable_on_vim_startup = 0
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']

set laststatus=2                 " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%y\ %{fugitive#statusline()}%m%r\ \ \ \ \ %l\ [%c-%v]\ %P

colorscheme raphael

" Mapping to set leader key  
let mapleader=","
let maplocalleader=","

" Mapping terminal command key for quick commands
nmap \ ;!

" Tab mappings.
map <leader>tn ;tabnew<cr>
map <leader>te ;tabedit
map <leader>tc ;tabclose<cr>
map <leader>to ;tabonly<cr>
map <leader>] ;tabnext<cr>
map <leader>[ ;tabprevious<cr>
map <leader>tf ;tabfirst<cr>
map <leader>tl ;tablast<cr>
map <leader>tm ;tabmove

" Finding all todos in project
map <leader>t ;Ack TODO --ignore-dir 'vendor' --ignore-dir 'log' --ignore-dir 'tmp' --ignore-dir 'public'<cr>
" Maps Enter to open QuickFixes currently selected file.
:autocmd BufReadPost quickfix nnoremap <buffer> <CR> <CR>

" Window mappings.
map <leader><Tab> <C-w>w 
map <leader>o <C-w>o
map <leader>v <C-w>v<C-w>w
map <leader>h <C-w>s<C-w>w
map <leader>p <C-w>p
map <leader>j <C-w>j
map <leader>k <C-w>k
map <leader>w <C-w>c
map <Leader>y ;%y+<cr>
map <up> <C-w>k
map <down> <C-w>j
map <left> <C-w>h
map <right> <C-w>l

" nmap <leader>r ;call ReloadAllSnippets()<cr>

" Mappings to commonly edited files
nmap <leader>1 ;e $HOME/bin/dotfiles/vim/vimrc<cr>
nmap <leader>2 ;e $HOME/bin/dotfiles/zsh/aliases<cr>
nmap <leader>3 ;e $HOME/bin/dotfiles/vim/colors/raphael.vim<cr>

if has("autocmd")
  autocmd bufwritepost vimrc source $HOME/bin/dotfiles/vim/vimrc " Automatically reloads vimrc when the file is saved.
endif

" Automatically save file when exiting insert mode
" imap <esc> <esc>;w<cr>	                  

" CtrlP  plugin mappings
nmap <silent> <leader>f ;CtrlP<cr>

" set notimeout          " don't timeout on mappings
" set ttimeout           " do timeout on terminal key codes
" set timeoutlen=100     " timeout after 100 msec

" NERDTree plugin mapping
map <leader>d ;NERDTreeToggle<cr>
let NERDTreeShowHidden=1

" Buffer Explorer plugin mapping
map <leader>b ;BufExplorer<cr>

" hexHighlight mapping
map <leader>c ;call HexHighlight()<cr>

" swap colon and semicolon for easier commands
nnoremap ; :
nnoremap : ;

vnoremap ; :
vnoremap : ;

" Mappings to make text indentation in command mode easier
nnoremap > >>
nnoremap < <<

" Mappings to make text indentation in visual mode easier
vmap > >gv
vmap < <gv

" Insert mode mappings
" set macmeta
imap ≥  <space>=> 
imap ≤ <%= %>
imap <C-Space> %
imap <A-Space> %
" Ctrl-j/k deletes blank line below/above, and Alt-j/k inserts.
nnoremap <silent><C-j> m`:silent +g/\m^\s*$/d<CR>``:noh<CR>
nnoremap <silent><C-k> m`:silent -g/\m^\s*$/d<CR>``:noh<CR>
nnoremap  :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <S-> :set paste<CR>m`O<Esc>``:set nopaste<CR>
nnoremap <silent>∆ :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <silent>˚ :set paste<CR>m`O<Esc>``:set nopaste<CR>

" Automatic fold settings for specific files. Uncomment to use.
set foldmethod=manual
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
" autocmd BufNewFile,BufRead *_spec.rb compiler rspec

" Sets up some global settings for the ragtag plugin 
let g:ragtag_global_maps = 1 

let g:UltiSnipsSnippetsDir = ["~/bin/dotfiles/vim/snippets"]
let g:UltiSnipsSnippetDirectories = ['snippets']
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" Sets the line height of the preview window
set previewheight=25

" Highlights the current line in all windows
set cursorline 
" Stop cursor blink in normal mode
set gcr=n:blinkon0

" Automatically saves files when the buffer is changed
set autowrite

" Changes the cursor shape in terminal vim (using iTerm2 on OS X)
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Auto indent entire file with Alt =
map   <silent> ≠ mmgg=G'm
imap  <silent> ≠ <Esc> mmgg=G'm

" Show syntax highlighting groups for word under cursor
nmap <C-S-P> ;call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val,"name")')
endfunc

" map jj o<esc>`a
" map kk O<esc>`a

" Mapping to remove all blank lines (whitespace)
nmap <leader>l ;g/^$/d<CR>

":command Thtml :%!tidy -q -i -html

" Add auto-expander for Handlebars template tags
imap {{ {{}}<Esc>hi

filetype indent off               " Turn off file indentation from plugins
let g:syntastic_javascript_checkers = ['jshint']

" Stops vim swapfile alert
set shortmess+=A

" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')

  " Silver Searcher compatibility with Vim.Ack
  let g:ackprg = 'ag --nogroup --nocolor --column'

  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

"""""""""""""""""""""""""""""""" NeoComplete
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 30
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Enable omni completion.
"autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
"autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
"autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
"autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
"autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif

let g:neocomplete#sources#omni#input_patterns.perl = '\h\w*->\h\w*\|\h\w*::'

" Map Ctrl j to next match
inoremap <expr><C-j> pumvisible() ? "\<C-n>" : "\<C-j>"
" Map Ctrl k to previous match
inoremap <expr><C-k> pumvisible() ? "\<C-p>" : "\<C-k>"
