" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

silent! call pathogen#runtime_append_all_bundles()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

" UNCOMMENT TO USE
set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs

set laststatus=2                 " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

colorscheme ir_black

" Mapping to set leader key  
" let mapleader = "`"
" let maplocalleader = "`"

" Tab mappings.
map <leader>t ;tabnew<cr>
map <leader>te ;tabedit
map <leader>tc ;tabclose<cr>
map <leader>to ;tabonly<cr>
map <leader>] ;tabnext<cr>
map <leader>[ ;tabprevious<cr>
map <leader>tf ;tabfirst<cr>
map <leader>tl ;tablast<cr>
map <leader>tm ;tabmove

" Window mappings.
map <leader>w <C-w>w 
map <leader>o <C-w>o
map <leader>v <C-w>v
map <leader>h <C-w>s
map <leader>p <C-w>p
map <leader>j <C-w>j
map <leader>k <C-w>k
map <leader>c <C-w>c

" CommandT  plugin mappings
nmap <silent> <leader>f ;CommandT<cr>
let g:CommandTMatchWindowAtTop=1
let g:CommandTCancelMap='<Esc>'
let g:CommandTSelectPrevMap=['<Esc>OA', '<Up>']
let g:CommandTSelectNextMap=['<Esc>OB', '<Down>']
let g:CommandTMaxHeight=25
" set notimeout          " don't timeout on mappings
" set ttimeout           " do timeout on terminal key codes
" set timeoutlen=100     " timeout after 100 msec

" NERDTree plugin mapping
map <leader>d ;NERDTreeToggle<cr>

" Buffer Explorer plugin mapping
map <leader>b ;BufExplorer<cr>

" swap colon and semicolon for easier commands
nnoremap ; :
nnoremap : ;

vnoremap ; :
vnoremap : ;

" Mappings to make text indentation in command mode easier
nnoremap > >>
nnoremap < <<

" Mappings to make text indentation in visual mode easier
vmap > >gv
vmap < <gv

" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
" autocmd BufNewFile,BufRead *_spec.rb compiler rspec

" Sets up some global settings for the ragtag plugin 
let g:ragtag_global_maps = 1 
