. ~/bin/dotfiles/zsh/config
. ~/bin/dotfiles/zsh/aliases

unsetopt correct_all

# node / nvm
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="$HOME/.cargo/bin:/usr/local/bin:/opt/homebrew/bin:$PATH:$HOME/bin:/opt/homebrew/opt/python@3.11/libexec/bin"

# starship
eval "$(starship init zsh)"
